export const state = {
  isTranslated: false,
  isTranslating: false,
  isObserverBusy: false,
  translatedElements: new Set(),
  statusEl: null,
  hideTimer: null,
  observer: null,
  pendingNodes: new Set(),
  observerTimer: null,
  cachedSettings: null,
  localCache: {},
  lazyObserver: null,
  lazyObserverTimer: null,
  pendingLazyBlocks: new Set(),
  elementToBlockMap: new WeakMap(),
  LLM_ENGINES: new Set(["gemini", "chatgpt", "openai", "claude", "ollama"]),
  SKIP_TAGS: new Set(["SCRIPT", "STYLE", "NOSCRIPT", "SVG", "MATH", "CODE", "PRE", "TEXTAREA", "INPUT", "SELECT", "IFRAME", "CANVAS", "VIDEO", "AUDIO", "BR", "HR", "META", "LINK", "HEAD", "TEMPLATE", "RT", "RP"]),
  INLINE_TAGS: new Set(["ABBR", "B", "BDO", "BIG", "CITE", "DFN", "EM", "I", "KBD", "MARK", "Q", "S", "SAMP", "SMALL", "STRONG", "SUB", "SUP", "U", "VAR", "WBR", "TIME", "DATA", "SPAN", "FONT", "RUBY"]),
  COMPLEX_ANCESTOR_SEL: "svg, canvas, video, audio, iframe, picture, object, embed, select, textarea, input, noscript",
  COMPLEX_CHILD_SEL: "img, svg, canvas, video, audio, picture, source, iframe, object, embed, input, select, textarea",
  HIDDEN_ANCESTOR_SEL: "[class*=\"sr-only\" i], [class*=\"visually-hidden\" i], [aria-hidden=\"true\"], [hidden]",
  BATCH_SIZE: 8,
  activeDictPopup: null,
  dictCache: new Map(),
  dictRateLimitUntil: 0,
  currentPopupContext: null,
};

export function isLLMEngine(mode) { return state.LLM_ENGINES.has((mode || "").toLowerCase()); }
